// Generated by deploy script
import { type Abi } from 'viem'

export type ActivityValidatorConfig = {
  address: `0x${string}`;
  abi: Abi;
}

export type ActivityValidatorFunctions = {
  proximityMultiplier(): Promise<bigint>;
  setProximityMultiplier(_multiplier: bigint): Promise<void>;
  setShouldValidateActivity(_should: boolean): Promise<void>;
  shouldValidateActivity(): Promise<boolean>;
  validateActivity(arg: bigint, arg2: `0x${string}`, arg3: any): Promise<boolean>;
  validateProximity(arg: bigint, arg2: `0x${string}`[], arg3: `0x${string}`[]): Promise<bigint>;
}

export type ActivityValidatorEvents = {
}
