// Generated by deploy script
import { type Abi } from 'viem'

export type FDollarsConfig = {
  address: `0x${string}`;
  abi: Abi;
}

export type FDollarsFunctions = {
  allowance(owner: `0x${string}`, spender: `0x${string}`): Promise<bigint>;
  approve(spender: `0x${string}`, amount: bigint): Promise<boolean>;
  balanceOf(account: `0x${string}`): Promise<bigint>;
  decimals(): Promise<number>;
  decreaseAllowance(spender: `0x${string}`, subtractedValue: bigint): Promise<boolean>;
  increaseAllowance(spender: `0x${string}`, addedValue: bigint): Promise<boolean>;
  mint(to: `0x${string}`, amount: bigint): Promise<void>;
  name(): Promise<string>;
  symbol(): Promise<string>;
  totalSupply(): Promise<bigint>;
  transfer(to: `0x${string}`, amount: bigint): Promise<boolean>;
  transferFrom(from: `0x${string}`, to: `0x${string}`, amount: bigint): Promise<boolean>;
}

export type FDollarsEvents = {
  Approval: {
    owner: `0x${string}`;
    spender: `0x${string}`;
    value: bigint;
  };
  Transfer: {
    from: `0x${string}`;
    to: `0x${string}`;
    value: bigint;
  };
}
