// Generated by deploy script
import { type Abi } from 'viem'

export type FitFiConfig = {
  address: `0x${string}`;
  abi: Abi;
}

export type FitFiFunctions = {
  ADMIN_FEE_BPS(): Promise<bigint>;
  activityValidator(): Promise<`0x${string}`>;
  calculateRewards(poolId: bigint, user: `0x${string}`): Promise<bigint>;
  closePool(poolId: bigint): Promise<void>;
  createPool(startTime: bigint, duration: bigint): Promise<void>;
  deposit(poolId: bigint, amount: bigint): Promise<void>;
  depositToken(): Promise<`0x${string}`>;
  getPoolTotalActivityPoints(poolId: bigint): Promise<bigint>;
  getPoolTotalDeposits(poolId: bigint): Promise<bigint>;
  getUserActivityPoints(poolId: bigint, user: `0x${string}`): Promise<bigint>;
  getUserDeposit(poolId: bigint, user: `0x${string}`): Promise<bigint>;
  owner(): Promise<`0x${string}`>;
  poolCounter(): Promise<bigint>;
  pools(arg: bigint): Promise<bigint | bigint | bigint | bigint | boolean | `0x${string}`>;
  renounceOwnership(): Promise<void>;
  submitActivity(poolId: bigint, proof: any, nearbyUsers: `0x${string}`[], proximityProofs: `0x${string}`[]): Promise<void>;
  totalActivityPoints(arg: bigint): Promise<bigint>;
  transferOwnership(newOwner: `0x${string}`): Promise<void>;
  userMultipliers(arg: bigint, arg2: `0x${string}`): Promise<bigint>;
  withdraw(poolId: bigint): Promise<void>;
  yieldProtocol(): Promise<`0x${string}`>;
}

export type FitFiEvents = {
  ActivitySubmitted: {
    poolId: bigint;
    user: `0x${string}`;
    points: bigint;
  };
  Deposited: {
    poolId: bigint;
    user: `0x${string}`;
    amount: bigint;
  };
  MultiplierApplied: {
    poolId: bigint;
    users: `0x${string}`[];
    multiplier: bigint;
  };
  OwnershipTransferred: {
    previousOwner: `0x${string}`;
    newOwner: `0x${string}`;
  };
  PoolCreated: {
    poolId: bigint;
    startTime: bigint;
    endTime: bigint;
  };
  RewardsClaimed: {
    poolId: bigint;
    user: `0x${string}`;
    amount: bigint;
  };
  Withdrawn: {
    poolId: bigint;
    user: `0x${string}`;
    principal: bigint;
    rewards: bigint;
  };
}
